name: test_sliver_provider
description: A new Flutter application.

publish_to: 'none'

version: 0.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
